export const SET_COUNTER = 'SET_COUNTER';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const PRESSED_HELLO_BUTTON = 'PRESSED_HELLO_BUTTON';
